- name: Copy System Configs for LFS Nodes
  gather_facts: true
  hosts: all
  tasks:
    - name: Display the node name
      debug:
        msg: "Node name: {{ inventory_hostname }}"

    - name: Start system_conf.yml
      include_role:
        name: ansible-gdt
        tasks_from: system_conf.yml