- name: Ensure user 'jenkins' exists
  ansible.builtin.user:
    name: jenkins
    state: present

- name: Create Jenkins Workdir
  ansible.builtin.file:
    path: /opt/jenkins
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Create Jenkins Agent Home
  ansible.builtin.file:
    path: /opt/jenkins/home
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Create Jenkins Agent Workdir
  ansible.builtin.file:
    path: /opt/jenkins/workdir
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Java
  ansible.builtin.apt:
    name: openjdk-17-jdk
    state: present

- name: Create SystemD unit for start Jenkins agent
  ansible.builtin.template:
    src: jenkins-agent.service.j2
    dest: /etc/systemd/system/jenkins-agent.service
    owner: root
    group: root
    mode: '0644'

- name: Start and enable Jenkins agent service
  ansible.builtin.systemd:
    name: jenkins-agent
    state: started
    enabled: true