- name: Create tmp directory
  ansible.builtin.file:
    path: /mnt/lfs/sources/conf_tmp 
    state: directory
    mode: '0755'

- name: Create kernel_configs directory
  ansible.builtin.file:
    path: /mnt/lfs/sources/kernel_configs 
    state: directory
    mode: '0777'

- name: Copy udev_systemd-257.3.sh
  ansible.builtin.copy:
    src: udev_systemd-257.3.sh
    dest: /mnt/lfs/sources/udev_systemd-257.3.sh
    mode: '0755'

- name: Copy shadow-4.17.3.sh
  ansible.builtin.copy:
    src: shadow-4.17.3.sh
    dest: /mnt/lfs/sources/shadow-4.17.3.sh
    mode: '0755'

- name: Copy strip.sh
  ansible.builtin.copy:
    src: strip.sh
    dest: /mnt/lfs/sources/strip.sh
    mode: '0755'

- name: Copy prepare_image.sh
  ansible.builtin.copy:
    src: prepare_image.sh
    dest: /mnt/lfs/sources/prepare_image.sh
    mode: '0755'

- name: Copy k8s init script
  ansible.builtin.copy:
    src: k8s.init
    dest: /mnt/lfs/sources/k8s.init
    mode: '0755'

- name: Copy etcd init script
  ansible.builtin.copy:
    src: etcd.init
    dest: /mnt/lfs/sources/etcd.init
    mode: '0755'

- name: Copy fake-csr
  ansible.builtin.copy:
    src: fake-csr.conf
    dest: /tmp/fake-csr.conf
    mode: '0755'

- name: Copy sshd init script
  ansible.builtin.copy:
    src: sshd.init
    dest: /mnt/lfs/sources/conf_tmp/sshd.init
    mode: '0755'

- name: Copy sshd_config
  ansible.builtin.copy:
    src: sshd_config
    dest: /mnt/lfs/sources/conf_tmp/sshd_config
    mode: '0644'

- name: Copy profile
  ansible.builtin.copy:
    src: profile
    dest: /mnt/lfs/sources/conf_tmp/profile
    mode: '0644'

- name: Copy kernel_config_x86_64
  ansible.builtin.copy:
    src: kernel_config_x86_64
    dest: /mnt/lfs/sources/kernel_configs/kernel_config_x86_64 
    mode: '0644'

- name: Copy sysctl.conf
  ansible.builtin.copy:
    src: sysctl.conf
    dest: /mnt/lfs/sources/conf_tmp/sysctl.conf
    mode: '0644'

- name: Copy hosts file
  ansible.builtin.copy:
    src: hosts
    dest: /mnt/lfs/sources/conf_tmp/hosts
    mode: '0644'

- name: Copy crio.conf
  ansible.builtin.copy:
    src: crio.conf
    dest: /mnt/lfs/sources/conf_tmp/crio.conf
    mode: '0644'

- name: Copy crio.init
  ansible.builtin.copy:
    src: crio.init
    dest: /mnt/lfs/sources/conf_tmp/crio.init
    mode: '0755'

- name: Copy policy.json
  ansible.builtin.copy:
    src: policy.json
    dest: /mnt/lfs/sources/conf_tmp/policy.json
    mode: '0644'